// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const title: string;
export const btnList: string;
export const repo: string;
